name: Check conactions

on:
  push:
    branches:
      - 'develop'
    paths:
      - '.github/workflows/check-connection.yml'
          
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: 
          - linux/amd64
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Bash check
        run: |
           env
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_TMP }}
          password: ${{ secrets.DOCKERHUB_TOKEN_TMP }}